CREATE TABLE [dbo].[Commentaire]
(
   Id INT NOT NULL PRIMARY KEY IDENTITY,
   Contenu VARCHAR(MAX) NOT NULL,
   Jaime INTEGER NOT NULL DEFAULT 0,
   DateCreation DATETIME NOT NULL DEFAULT GETDATE(),
   Post_Id INT NOT NULL,
   User_Id UNIQUEIDENTIFIER NOT NULL,
   FOREIGN KEY(Post_Id) REFERENCES Post(Id),
   FOREIGN KEY(User_Id) REFERENCES [User](Id)
)
