CREATE TABLE [dbo].[Post]
(
   Id INT NOT NULL PRIMARY KEY IDENTITY,
   Contenu VARCHAR(MAX) NOT NULL,
   Jaime INTEGER NOT NULL DEFAULT 0,
   Partage INTEGER NOT NULL DEFAULT 0,
   DateCreation DATETIME NOT NULL DEFAULT GETDATE(),
   Image1 VARCHAR(MAX),
   Image2 VARCHAR(MAX),
   Image3 VARCHAR(MAX),
   Image4 VARCHAR(MAX),
   User_Pseudo VARCHAR(50) NOT NULL,
   CONSTRAINT FK_UserPost FOREIGN KEY (User_Pseudo) REFERENCES [User](Pseudo)
)
